### PR TITLE
Added a method that allow to set a String instead a int from resources

### PR DESCRIPTION
**Pull request by ppamorim**
I need this on my project. Because I need create the title dynamically.
Can you merge this?

### CODE REVIEW

**Comment by ogaclejapan** [comment]
Hi, @ppamorim 
Thank you for PR

Hmm, Do not you can do the same in this code?

```java

 FragmentPagerItems.with(this)
    .add(FragmentPagerItem.of("title", PageFragment.class))
    .create());

```

**Comment by ppamorim** [comment]
Hi @ogaclejapan 
Why I need add this complexity to the code? My changes are more expressive.

**Comment by ogaclejapan** [comment]
Hi, @ppamorim 
I fix the code: https://github.com/ogaclejapan/SmartTabLayout/commit/60a9957822a45158c6e63686c517baf4a99f9191
Sorry, because unnecessary file has been commit, I will fix.

**Comment by ogaclejapan** [comment]
If there is no problem in this implementation will sync to the master.

**Comment by ogaclejapan** [comment]
Right now, merge to master. https://github.com/ogaclejapan/SmartTabLayout/commit/60a9957822a45158c6e63686c517baf4a99f9191

**Pull request closed without merging**
