### PR TITLE
-Added OnTabClickListener for user click on the tab event.

### PR DESCRIPTION
**Pull request by jutikorn**

### CODE REVIEW

**Comment by ogaclejapan** [comment]
Hi, @jutikorn 
Thank you for PR.

When the tab is selected, `ViewPager.OnPageChangeListener#onPageSelected(...)` event will raise.
What you want to animate only when clicked?

**Comment by jutikorn** [comment]
Hi @ogaclejapan,
I would like to do something when user click on the tab. For example: bring the listView or RecyclerView to the top. :)

**Comment by Ki41foo** [comment]
Here is a tiny problem when clicking tab item after scrolling tablayout. Tablayout would scroll based on page selected every time. So I separate the tab click event for this situation. 

---------------------------
//separate tab click tab movement from page selected tab movement
    boolean isTabClicking = false;

    private class TabClickListener implements OnClickListener {
        @Override
        public void onClick(View v) {
            isTabClicking = true;

            int position = 0;
            for (int i = 0; i < mTabStrip.getChildCount(); i++) {
                if (v == mTabStrip.getChildAt(i)) {
                    mViewPager.setCurrentItem(i);
                    position = i;
                    break;
                }
            }

            //just scroll to selected position directly
            scrollToTab(position, 0);
        }
    }
-------------------------------

@Override
        public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
            ...
            ...

            //scroll tab only when page dragging
            if(!isTabClicking)
            scrollToTab(position, extraOffset);

           ...
}

------------------------------

@Override
        public void onPageScrollStateChanged(int state) {
            ...
            //restore tab click state
            if( isTabClicking && state == ViewPager.SCROLL_STATE_IDLE  && !mTabStrip.isIndicatorAlwaysInCenter()) {
                isTabClicking = false;
            }
        }


And thanks for your work.

**Comment by ogaclejapan** [comment]
Hi, @Ki41foo 
Thank you for comment.
The very would be helpful :+1: 

Hmm,
If support this feature, It state control is complicated...

Let me think about it.

**Comment by Ki41foo** [comment]
Yeah. It works fine for my case. But for more common situation it should be considered thoroughly.

**Comment by ogaclejapan** [comment]
implemented in #68 #74

**Pull request closed without merging**
